apiVersion: argoproj.io/v1alpha1
kind: Rollout  
metadata:  
  name: apache-ro  
  namespace: apache-ns
spec:  
  replicas: 10 
  selector:  
    matchLabels:  
      app: apache  
  template:  
    metadata:  
      labels:  
        app: apache  
    spec:  
      containers:  
      - name: apache  
        image: httpd:2.4.55  
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: {duration: 30s}
